package id.web.izs.sqlclient.util

import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM encryption for stored credentials. Pure JVM logic on top of an
 * injected [SecretKey] (production keys come from the Android Keystore via
 * [KeystoreKeyProvider]) so the format itself is unit-testable on the JVM.
 *
 * Payload format: Base64( iv(12 bytes) || ciphertext+tag(16 bytes) ).
 */
class CredentialCrypto {
    companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }

    fun encrypt(key: SecretKey, plaintext: String): String {
        // The IV must be generated by the crypto provider (cipher.iv), never
        // caller-supplied: Android Keystore keys created with
        // setRandomizedEncryptionRequired(true) reject a caller-provided IV
        // with "Caller-provided IV not permitted". Provider-generated IVs work
        // on plain JVM keys too, so this stays unit-testable.
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(Cipher.ENCRYPT_MODE, key)
        }
        val iv = cipher.iv
        require(iv != null && iv.size == IV_BYTES) { "Provider did not generate a 12-byte GCM IV" }
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        return Base64.getEncoder().encodeToString(iv + ciphertext)
    }

    fun decrypt(key: SecretKey, payload: String): String {
        val raw = Base64.getDecoder().decode(payload)
        require(raw.size > IV_BYTES) { "Credential payload too short" }
        val cipher = Cipher.getInstance(TRANSFORMATION).apply {
            init(
                Cipher.DECRYPT_MODE, key,
                GCMParameterSpec(TAG_BITS, raw, 0, IV_BYTES)
            )
        }
        val plaintext = cipher.doFinal(raw, IV_BYTES, raw.size - IV_BYTES)
        return plaintext.toString(Charsets.UTF_8)
    }
}
